apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mcad-pipeline
spec:
  params:
  - default: {{ .Values.global.app.mcad.repo }}
    description: The application git repository
    name: APP_SOURCE_GIT
    type: string
  - default: main
    description: The application git revision
    name: APP_SOURCE_REVISION
    type: string
  tasks:
  - name: source-clone-mcad
    params:
    - name: url
      value: $(params.APP_SOURCE_GIT)
    - name: revision
      value: $(params.APP_SOURCE_REVISION)
    - name: depth
      value: "0"
    - name: subdirectory
      value: multi-cluster-app-dispatcher
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace

  - name: build-app
    runAfter:
    - source-clone-mcad
    taskRef:
      kind: Task
      name: mcad-build
    workspaces:
    - name: source
      workspace: workspace
  
  - name: build-image
    params:
    - name: IMAGE
      value: 'image-registry.openshift-image-registry.svc:5000/test/multi-cluster-app-dispatcher'
    - name: TLSVERIFY
      value: 'false'
    - name: CONTEXT
      value: '/workspace/source/multi-cluster-app-dispatcher'
    runAfter:
    - build-app
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace

  workspaces:
  - name: workspace

  # - name: buildah-image
  #   runAfter:
  #   - build-app
  #   taskRef:
  #     kind: ClusterTask
  #     name: buildah
  #   workspaces:
  #   - name: source
  #     workspace: workspace
  # workspaces:
  # - name: workspace
